# Set folder to clover (must be the same on travis)
coverage_clover: api/var/coverage/clover.xml
# Same folder here
json_path: api/var/coverage/coveralls-upload.json
# Don't touch that
service_name: travis-ci
