language: php

php:
  - 7.4

# faster builds on new travis setup not using sudo
sudo: false

services:
  - postgresql

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer update --dev --prefer-dist --no-interaction --working-dir=api

before_script:
  - mysql -e 'CREATE DATABASE yii2advanced_test;'
  - psql -c 'create database travis_ci_test;' -U postgres
  - php api/bin/app.php migrations:migrate --no-interaction

script:
- api/vendor/bin/phpunit -c api/phpunit.xml
